import Header from '@/components/layout/Header';
import type { Metadata } from 'next';
import { League_Spartan } from 'next/font/google';
import './globals.css';

const spartan = League_Spartan({
  variable: '--font-spartan',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${spartan.variable} antialiased overflow-x-hidden`}>
        <Header />
        <main className='h-[1000px]'>{children}</main>
      </body>
    </html>
  );
}
