import type { Metadata } from 'next';
import { League_Spartan } from 'next/font/google';
import './globals.css';
import Header from '@components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const spartan = League_Spartan({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${spartan.className} antialiased min-h-[100dvh]`}>
        <div className='relative overflow-hidden'>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
